basePath: /
definitions:
  auth.FailureResponse:
    properties:
      message:
        example: Email or Password is wrong
        type: string
      success:
        example: false
        type: boolean
    type: object
  auth.SuccesResponse:
    properties:
      message:
        example: Login Succes
        type: string
      success:
        example: true
        type: boolean
      token:
        example: jhdfkjsbgakjhgsgkhksjgb
        type: string
    type: object
  request.LoginRequest:
    properties:
      email:
        example: conthjoh@emle.com
        type: string
      password:
        example: conthgjoh_passrd
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This API is for tracking your finance
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Finance Tracker API
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Usage of this endpoint will allow user to login and get JWT token
      parameters:
      - description: User login information
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login success
          schema:
            $ref: '#/definitions/auth.SuccesResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/auth.FailureResponse'
      summary: Login User
      tags:
      - Authentication
swagger: "2.0"
